export const MESSAGE_ENUM = Object.freeze({
  SELF_CONNECTED: "SELF_CONNECTED",
  START_FETCH: "START_FETCH",
  SUCCESS_FETCH: "SUCCESS_FETCH",
  FAILED_FETCH: "FAILED_FETCH",
});

export const PORT = 9290;
